---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1t8gfvnm555sddz6vczj028stv4wksgak7jp72anjtcsfplzxxuesxpq4w2
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1t8gfvnm555sddz6vczj028stv4wksgak7jp72anjtcsfplzxxuesxpq4w2
