# from https://www.debontonline.com/2021/11/kubernetes-part-16-deploy-jellyfin.html
---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-udp
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: jellyfin
spec:
  selector:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  ports:
    - port: 1900
      targetPort: 1900
      name: dlna-udp
      protocol: UDP
    - port: 7359
      targetPort: 7359
      name: discovery-udp
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 192.168.178.222
  sessionAffinity: ClientIP
