---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: download
spec:
  releaseName: nzbhydra2
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbhydra2
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbhydra2
      tag: v3.18.3
    env:
      TZ: "Europe/Berlin"
    probes:
      startup:
        enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
#          kubernetes.io/tls-acme: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: nfc-search-variant
          cert-manager.io/cluster-issuer: letsencrypt-production
#          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
#          traefik.ingress.kubernetes.io/router.middlewares: "network-internal-auth@kubernetescrd"
#          external-dns/is-public: "true"
#          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: "nzbhydra.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "nzbhydra.${SECRET_DOMAIN}"
            secretName: nzbhydra-tls
    persistence:
      config:
        enabled: true
    resources:
      requests:
        memory: 250Mi
        cpu: 200m
      limits:
        memory: 1500Mi
