---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbget
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbget
      tag: v21.1
#    service:
#      main:
#        type: LoadBalancer
#        loadBalancerIP: 10.0.6.52
    env:
      TZ: "Europe/Berlin"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/icon: download-circle-outline
        hosts:
          - host: nzbget.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "nzbget.${SECRET_DOMAIN}"
            secretName: nzbget-tls
    persistence:
      config:
        enabled: true
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /volume1/media
        mountPath: /media
#    podSecurityContext:
#      runAsUser: 1001
#      runAsGroup: 1001
#      fsGroup: 1001
#    podAnnotations:
#      backup.velero.io/backup-volumes: config
#    tolerations:
#      - key: "arm"
#        operator: "Exists"
    resources:
      requests:
        memory: 250Mi
        cpu: 50m
      limits:
        memory: 600Mi
