---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ckotzbauer.github.io/helm-charts/
      chart: nfs-client-provisioner
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: ckotzbauer-charts
        namespace: flux-system
      interval: 5m
  # https://github.com/ckotzbauer/helm-charts/tree/main/charts/nfs-client-provisioner
  values:
    nfs:
      server: 192.168.178.101
      path: /volume1/k3s-home
    storageClass:
      defaultClass: true
