kind: Secret
ansible_user: ENC[AES256_GCM,data:jKgapnSc,iv:X1PDwnzxl9B4UYnR7SO8NzuAQr2JC9GM/t4O2hewpPg=,tag:EXYptjdUtDtYEflePxfdIQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:s/6pZyD/8j1Uh+JIGY7pXgDDYr03lxp5yJg3X7EB,iv:8K0vAcQfq7sH5T4/191obXBK69cxWBa8bdqi+d80/pg=,tag:wg1exn55Dpr6oZXlUvJnWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8gfvnm555sddz6vczj028stv4wksgak7jp72anjtcsfplzxxuesxpq4w2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWEUvQThQd3M0SE9FY0pv
            OC9oVE54VStHR3o3UTZqanBnOEw1YmQvemlzCk1ibjAvdDNWN0Uvb05IRjdwaXhJ
            YSttREZiMnhiSGRacG9iSnJ5VWk3Y2sKLS0tIDJqTkcvb0g3Z1BLNW5qa2RhOUdY
            UGZwMGJWYzNNa3pmbytZamtZZFVjWUEKrbYMMg9mizEsvWrmqWEkF47JT5qWjlO+
            qN35DtAy2DgD6YBLnocJpptb3q3v9xUbgzbhL+FUtVtT6HScrRGVGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-13T10:39:38Z"
    mac: ENC[AES256_GCM,data:F72rJwRsqPKRkrOlY2stVMkAFyv/ItYnl5QnfCQfZzTHFzslGTuu0CeJWeBNuU50mkCbm5X2RHGRlliJwcYVsSJF9B7QxN0TGmzSv1mY0tgcLvEDBTZCGG04y5M/rzVW4jcMJVzooHnTjVbVTl0BchszFFv6rJDmLWgPZK0gdAw=,iv:kXfC1Lpx3XLA813bPtFJuLMW+lqCGU2118bgLX+4wWc=,tag:zBSYqO9QscCU94UKoYXdYg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
