kind: Secret
ansible_user: ENC[AES256_GCM,data:VoERzlhV,iv:5OnQBxa9sTvjl/6aEMEjEHNTdJ+8rYFXDWCKAAqbclQ=,tag:EAb9vILUc0dv06tpjNhgAg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wEykRwtg,iv:Oze0lVH42QXakFiNpxeuveIJjoAG25vao62Z+uB7qUc=,tag:BtHXYzE7Pp+KO2Qzn+BD9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8gfvnm555sddz6vczj028stv4wksgak7jp72anjtcsfplzxxuesxpq4w2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQWwyeENCUEY3NzJYd2ZM
            aUR4VzBRWS8zdXd3SUh2ajVYSnYxUFZFLzE0Ci82czlHNHBkM0lBQXl3T0YzQmpI
            VlIySzJkRkVXU3lubzVvVml2N2piTmsKLS0tIFRpWGNPTjFBWGRyMCtYL1NPNFl0
            NGhwaUV3YjVlekw2WnJaRGVXMEloWTQK3dhi0TxprnomHtdxB1h+1WTNO7IUDXXp
            hVRjpT/o+NrPVmL2mpG+TRZHZ5f3AsgXSgTAKmmvM0gE7eHwPs5Srg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-22T09:57:42Z"
    mac: ENC[AES256_GCM,data:x+ptgAQAgGZvv86VasQUhaimz9kSPa2BHqTCP2PiAcztc7/VQS3V1jfruVoJQMcJ6YZBefKWJK5FACoUJ1/oMbDozThMQx61CmkgUT23KZkQ2s5OhgL77FgyWnLoGP9rLmcmbT3C3NP86jHN62radArzsRefCQd7MYAGSOJeWys=,iv:3blK3wdguPUaaYecrYBBNw35g8lceVTj9NPQkATx/lM=,tag:BgS50RQQNklHwJRWZm0b/Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
