---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  NAS_ADDR: 192.168.178.99
  #
  METALLB_LB_RANGE: 192.168.178.220-192.168.178.230
  METALLB_TRAEFIK_ADDR: 192.168.178.220
