# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:85KzWuPFeSKVWeo2BjQ=,iv:whutMlHTz8r+9D9H4KVYnfZTpiUtyzsKWAzn4qSkTMw=,tag:bLbph41a33ImJxQLcLHrxg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Jh3kgDuaDZ5PEoVsZ9GfIlJw609MF1ltt1Ao/69fwQkiOEYOe3ls,iv:W8AOw0BxapOoqXHGRUiU1plOddBMexeRfd9PVf2b7yk=,tag:oGelSQW3wjq8ZUmOSWFo4w==,type:str]
    #
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:Ck5tbwmiR9oHuwqetCjNCEXJ,iv:XJQlrsPaNskXvGNXadB1zTxrniYH2NM6vZkZNi3BMYc=,tag:cID1URySkBLZRt/weuGmQw==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:Du+DgRO0qpmQL7wrYQB9zMjV,iv:NNaRdTIl370slBwa+GXZGW/0CtIB1ViDGphvs8yRXIU=,tag:3DPJPjeOTln0vdPMEtZA0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8gfvnm555sddz6vczj028stv4wksgak7jp72anjtcsfplzxxuesxpq4w2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidmdLeDVvS3g1YlZMbjZL
            ZHNZeHI5YWwzbVlPcHcxSGtSOFNzaVNrTWhZCmhHUkFEa2tjYm14TUdlU1NQcUcv
            VDJtWUx1dEFzSXV0NW9wVktPNWtVbEUKLS0tIFc4SjdMM2E4b0hmYUZpcWgvODNL
            d2NGb0hzVzRLdUZxSDRLK3A4ZHowdlUKewMkvmqDIOeiP7FyEOQEHK8uTHFzVaiT
            ZSXrhJ2tQiO6045soA53jnRSMFSIeHycToGJbXoeDtUephx1pMwMjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-13T10:39:38Z"
    mac: ENC[AES256_GCM,data:1WNnfM53wF1DojLq0nuYzT8ykgZrTYbstO/D+AA/XZ91NATAkXiPdL6HOPNYrD5xOUjn2UOLakjq6rYHTm25srIWM8gJfXpZHwmzS+am5fPRpvUZSgXoIlJgKPlqhBGRFEi/0o/jOC0rM+kg4LMAkjnprLRranvKcSvCBK4pd3E=,iv:F+FwuSN2G+uCzeBBORMP8m7M15xAnEOTCdElGfn1mzA=,tag:lY+Wo5Y7YiEFu8C6aDrnUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
