# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:gHzD2TnD1ib71U3/dl8=,iv:kAwZRR9vkKqHgCBTr7wmyn/tzXm9jMQzHPMWZ7eno1g=,tag:QPccdhgQzY1uYnA7mdZA4A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:N7MUFmihy/qQdEA3jyH1URBRD5j2Pghf+UQqM2O4cdG2/yWw6ah/,iv:evxeIoWHlUfo4bKledIk5KcADuQ90DENbfAKgt+pTNA=,tag:WxImJqS1i+/x2PSdyZ57sQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8gfvnm555sddz6vczj028stv4wksgak7jp72anjtcsfplzxxuesxpq4w2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MTA2czFkLzM5WUZrTW9Q
            YzJnTzE2VFBVckVCYjZ6eFRjS3BNTFFhQWtNCjc3YnQ0eWtBczB1UXVlVEwreEVp
            ZFFnUk9sbmN1REFhQ1BaM2VuQTMyanMKLS0tIFM3b1VSeXJsSHV1N1lQZlBPYXNO
            UGdkYzRxcFJFaTY0MVF0SERvRG9nQjAKlTv9sF24k4sIGzk+KbIKSSp/3FVfEGZG
            zBxJzZP3yzcNExA/6JBJWJMZezjJRzx+Z0ESNK3QtUxAsV25+MLK6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-02T11:02:56Z"
    mac: ENC[AES256_GCM,data:o29yljJgsrxDiPyioMiSJQFcBSHPRaPlES8svpaBNJzN+m+GJTPpeSZWT75OTLNF4i+5rFeHX09KNJpkH1v/zpLlDa2OoqL9mAuGI2hMIogMSra3kqwPAs8eEujgETZiSEaW7mt20lbH35t8Rp3aal4r5IyPtL/3L5wgYi3gVD8=,iv:R6I4SeEOcjI6uX7CGp43ILGE9InSy9DGmGutfhd0QBQ=,tag:74sMaNssmU2+f9AJAw3W8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
