# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:iI5XkkI0Kih6IgBQBjs=,iv:AXXQoobC1/pNs5wIaTXI0YxmeUNjpuoVYCfHs3nB9+o=,tag:HhI8Hsvx8a9DINf2/TXfqg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OY9wEgJW9v/EbM5WB8leRFP8aoMTHqsNFU6a1utP7Haw3U5IGhPP,iv:rXmNZc7zYL/JXgAitwMI5Fn25POyHh1Qkp+nLvYhf68=,tag:zs5QqU0KQNlVP4Sy8bHC/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8gfvnm555sddz6vczj028stv4wksgak7jp72anjtcsfplzxxuesxpq4w2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWG1OLzNzWTdFRERhWEtC
            VzJkK3ZzYXNLeXJ1MWtvN3lCbHNrRFFmcFV3ClpZRUxzZXpVRWk5blVXM2UxbDVE
            Ui9BaVZodWpKdHBtTURRZzdiRW1RRFEKLS0tIEtiQ2ZmVUNxLzN4blM4RjJSbms2
            bSsyVitzdk9EMlM5U3VDYlV0ajBHaTAKH0ow9OURQfcKrgfbNDKLqzYVZAoOsb+i
            3DPkF+lhIchjVYSDnWPgflGSb5xOTSFhLeGi3Qnir4QNnvwdO+RHWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-08T22:15:09Z"
    mac: ENC[AES256_GCM,data:D//UuuHfch0CTxHwHflANb49qLaryzxPf/SDspNBBKN2i7EK+uZXkhfoFvKTzk1iniH/beXZ2+4m5cU5sIjhXZEazP2LYMnUlG/nK5fyTsCItgVPeZS586xKpseWZuDX4e+449bWRUDdrXQDK+62wSujXE25gD6rXwJJehLWGeQ=,iv:UK2fzucGFckDrsilmozSHdoeKJZh4lltqQ0yAt6RTiA=,tag:7HP2fgUR1O8EqHKfUwOeRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
