---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-volume1-media
  namespace: media
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi # < Maximum storage size you want to reserve
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: "${NAS_ADDR}"
    path: /volume1/k3s-home
    readOnly: false
