---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    addons:
      vpn:
        enabled: true
        type: wireguard
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ $(wget -q -O- https://ipinfo.io/country) == 'FI' ]; then exit 0; else exit $?; fi
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 1
        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                # VPN traffic port - change if your provider uses a different port
                - port: 51820
                  protocol: UDP
            - to:
                - ipBlock:
                    cidr: 169.254.1.1/32
                - ipBlock:
                    cidr: 172.22.0.0/12
                - ipBlock:
                    cidr: 10.32.0.0/16
                - ipBlock:
                    cidr: 10.33.0.0/16
                - ipBlock:
                    cidr: 192.168.178.0/24
        wireguard:
          image:
            repository: ghcr.io/k8s-at-home/wireguard
            tag: v1.0.20210914
            pullPolicy: IfNotPresent
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          capabilities:
            drop:
              - "SYS_MODULE"
        env:
          TZ: "Europe/Berlin"
          IPTABLES_BACKEND: nft
          KILLSWITCH: "true"
        configFileSecret: vpn-gateway-vpnconfig-wg-mullvad-fi1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
            cpu: 200m
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.4.0
    publicPorts:
      - hostname: qbittorrent
        IP: 21
        ports:
          - type: tcp
            port: "56059"
          - type: udp
            port: "56059"
    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.4.0
#      gatewayDefault: false
#      gatewayLabel: setGateway
#      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "routed-gateway"
    settings:
      VPN_INTERFACE: wg0
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_TRAFFIC_PORT: "51820"
      # Route internal K8s and local home traffic in to the defaullt K8S gateway
      # 169.254.1.1 fritz router
      # 172.16.0.0 vxlan
      # 192.168.178.0 home lan
      # 10.32.0.0 cluster cidr
      # 10.33.0.0 service cidr
      NOT_ROUTED_TO_GATEWAY_CIDRS: "169.254.1.1/32 172.16.0.0/12 10.32.0.0/16 10.33.0.0/16 192.168.178.0/24"
      VPN_LOCAL_CIDRS: "169.254.1.1/32 172.16.0.0/12 10.32.0.0/16 10.33.0.0/16 192.168.178.0/24"
      # Use a different VXLAN network segment that does not conflict with the above
#      VXLAN_IP_NETWORK: "192.168.242"
#      VXLAN_ID: 43
#      VXLAN_IP_NETWORK: 172.16.1
    routed_namespaces:
      - download
