---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.4.0
    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.4.0
      gatewayDefault: false
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
    settings:
      # Route internal K8s and local home traffic in to the defaullt K8S gateway
#      NOT_ROUTED_TO_GATEWAY_CIDRS: "192.168.178.0/24"
#      NOT_ROUTED_TO_GATEWAY_CIDRS: "172.22.0.0/12 192.168.178.0/24"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16 192.168.178.0/24"
#      VPN_LOCAL_CIDRS: "192.168.178.0/24"
      VPN_LOCAL_CIDRS: "10.42.0.0/16 10.43.0.0/16 192.168.178.0/24"
#      VPN_LOCAL_CIDRS: "172.22.0.0/12 192.168.178.0/24"
      # Use a different VXLAN network segment that does not conflict with the above
#      VXLAN_IP_NETWORK: "192.168.242"
    routed_namespaces:
      - vpn
